import { Inter } from "next/font/google";
import "./globals.css";
// import '../styles/global.css'
import { AuthProvider } from '@/context/AuthContext';
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          {/* <Header /> */}
          {children}
        </AuthProvider>
      </body>
    </html>
    </html>
  );
}
